//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "LogAssertCheck.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Lex/MacroArgs.h"
#include "clang/Lex/PPCallbacks.h"
#include "clang/Lex/Preprocessor.h"
#include "llvm/ADT/StringSet.h"

using namespace clang::ast_matchers;

namespace clang::tidy::cathexis {
namespace {

class LogAssertCallbacks : public PPCallbacks {
public:
  LogAssertCallbacks(ClangTidyCheck &Check, SourceManager &SM,
                     const LangOptions &LangOpts)
      : Check(Check), SM(SM), LangOpts(LangOpts) {}

  void MacroExpands(const Token &MacroNameTok, const MacroDefinition &,
                    SourceRange, const MacroArgs *) override;

private:
  ClangTidyCheck &Check;
  SourceManager &SM;
  const LangOptions &LangOpts;

  std::string PreviousMacro;
  SourceLocation PreviousLoc;
};

void LogAssertCallbacks::MacroExpands(const Token &MacroNameTok,
                                      const MacroDefinition &MD,
                                      SourceRange Range,
                                      const MacroArgs *Args) {
  auto *II = MacroNameTok.getIdentifierInfo();
  if (!II)
    return;

  std::string Current = II->getName().str();

  SourceLocation Loc = MacroNameTok.getLocation();

  if (!SM.isWrittenInMainFile(Loc))
    return;

  static const llvm::StringSet first_macros = {
      // "CDebugF",
      // "CDebug",
      "CLogF",
      "CLog",
  };

  static const llvm::StringSet second_macros = {
      "CHECKF",
      "CHECKF_M",
      "GASSERT_OPT",
      "GASSERT_OPT_M",
  };

  if (!first_macros.contains(Current) && !second_macros.contains(Current)) {
    PreviousMacro.clear();
    return;
  }

#if 0
  // This is trying to find a way to handle CDebugF, which is not 'functionLike'
  // and has no arguments, which means the NORM arg can't be checked

  llvm::errs() << "Current=" << Current << "\n";

  if (SM.isMacroBodyExpansion(Loc))
    llvm::errs() << " - generated by another macro\n";
  else
    llvm::errs() << " - NOT generated by another macro\n";

  if (const MacroInfo *MI = MD.getMacroInfo()) {
    llvm::errs() << " - FunctionLike=" << MI->isFunctionLike() << "\n"
                 << " - NumParams=" << MI->getNumParams() << "\n";

    if (!MI->isFunctionLike()) {
      llvm::errs() << " - Not function like - abort\n";
      return;
    }
  }

  if (Args != nullptr) {
    llvm::errs() << " - " << Args->getNumMacroArguments() << " args:\n";
    for (unsigned i = 0; i < Args->getNumMacroArguments(); ++i) {
      const auto *token = Args->getUnexpArgument(i);
      std::string name = std::string(SM.getCharacterData(token->getLocation()),
                                     token->getLength());

      llvm::errs() << "  - arg " << i << ": '" << name << "'\n";
    }
  } else {
    llvm::errs() << " - null args\n";
  }
#endif

  if (Args != nullptr && Args->getNumMacroArguments() > 0) {
    const auto *token = Args->getUnexpArgument(0);
    std::string name = std::string(SM.getCharacterData(token->getLocation()),
                                   token->getLength());

    if (name == "NORM")
      return;
  }

  if (first_macros.contains(PreviousMacro) && second_macros.contains(Current))
    Check.diag(Loc, PreviousMacro + " immediately followed by " + Current);

  PreviousMacro = Current;
  PreviousLoc = Loc;
}
} // namespace

void LogAssertCheck::registerPPCallbacks(const SourceManager &,
                                         Preprocessor *PP, Preprocessor *) {
  PP->addPPCallbacks(std::make_unique<LogAssertCallbacks>(
      *this, PP->getSourceManager(), PP->getLangOpts()));
}

} // namespace clang::tidy::cathexis
